Update 71087094.yml

diff --git a/.github/workflows/71087094.yml b/.github/workflows/71087094.yml
--- a/.github/workflows/71087094.yml
+++ b/.github/workflows/71087094.yml
@@ -10,5 +10,5 @@ jobs:
     steps:
       - name: Debug echo
         run: |
-          filename="MY_FILE.TXT"
-          echo "::error::Filename $filename doesn't match possible files" && exit 1
+          echo "::error::Epic Fail"
+          exit 1
